//! Wire-namespace parity: replays `tests/fixtures/hub_namespace_cases.json`
//! (generated by `tests/hub_namespace_parity.py` from the Python
//! `federation.public_payload`) against `hub::namespace` and demands 0 DIFF.
//! Cases the oracle rejects must be refused by `try_public_payload` with the
//! same text, while the lenient `public_payload` still answers.
use std::path::Path;

use serde_json::Value;
use sessiondock::hub::{
    namespace::{public_payload, qualify, split, try_public_payload},
    registry::Node,
};

fn node(row: &Value) -> Node {
    Node {
        url: "http://127.0.0.1:1".into(),
        token: "t".repeat(32),
        id: row["id"].as_str().unwrap().to_string(),
        name: row["name"].as_str().unwrap().to_string(),
        color: None,
        enabled: None,
    }
}

fn cases() -> Vec<Value> {
    let path =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/hub_namespace_cases.json");
    let raw = std::fs::read(&path).unwrap_or_else(|error| panic!("{}: {error}", path.display()));
    serde_json::from_slice(&raw).expect("fixture is JSON")
}

#[test]
fn public_payload_matches_the_python_oracle_on_every_case() {
    let cases = cases();
    assert!(cases.len() >= 40, "corpus has only {} cases", cases.len());
    let mut diff = Vec::new();
    let mut refused = 0;
    for case in &cases {
        let name = case["name"].as_str().unwrap();
        let path = case["path"].as_str().unwrap();
        let node = node(&case["node"]);
        let input = case["input"].clone();
        match case.get("error").and_then(Value::as_str) {
            Some(expected) => {
                refused += 1;
                match try_public_payload(input.clone(), &node, path) {
                    Err(error) if error.message() == expected => {}
                    Err(error) => diff.push(format!(
                        "{name}: refused with {error:?}, oracle {expected:?}"
                    )),
                    Ok(value) => diff.push(format!(
                        "{name}: accepted {value}, oracle raises {expected:?}"
                    )),
                }
                // The registry hook never fails; it keeps the reference as sent.
                let lenient = public_payload(input, &node, path);
                assert!(!lenient.is_null() || case["input"].is_null(), "{name}");
            }
            None => {
                let expected = &case["expected"];
                match try_public_payload(input.clone(), &node, path) {
                    Ok(value) if &value == expected => {}
                    Ok(value) => {
                        diff.push(format!("{name}:\n  rust   {value}\n  python {expected}"))
                    }
                    Err(error) => {
                        diff.push(format!("{name}: refused with {error:?}, oracle accepts"))
                    }
                }
                let lenient = public_payload(input, &node, path);
                if &lenient != expected {
                    diff.push(format!(
                        "{name} (lenient):\n  rust   {lenient}\n  python {expected}"
                    ));
                }
            }
        }
    }
    println!(
        "hub_namespace parity: {} cases ({refused} refused), DIFF {}",
        cases.len(),
        diff.len()
    );
    assert!(diff.is_empty(), "DIFF {}:\n{}", diff.len(), diff.join("\n"));
}

#[test]
fn scoped_references_in_the_corpus_split_back_to_their_locals() {
    // Every uid the oracle produced round-trips through `split`, and
    // re-qualifying the local gives the wire form again.
    let mut seen = 0;
    for case in cases().iter().filter(|case| case.get("expected").is_some()) {
        let nid = case["node"]["id"].as_str().unwrap();
        let mut stack = vec![&case["expected"]];
        while let Some(value) = stack.pop() {
            match value {
                Value::Array(items) => stack.extend(items),
                Value::Object(map) => {
                    for (key, value) in map {
                        if ["data", "content", "input", "arguments", "raw", "resolved"]
                            .contains(&key.as_str())
                        {
                            continue;
                        }
                        if let (true, Some(text)) = (
                            ["uid", "from_uid", "to_uid", "continued_in"].contains(&key.as_str()),
                            value.as_str(),
                        ) && !text.is_empty()
                        {
                            let (node, local) =
                                split(text, true).unwrap_or_else(|error| panic!("{text}: {error}"));
                            assert_eq!(node, nid, "{text}");
                            assert_eq!(qualify(nid, &local, true).unwrap(), text);
                            seen += 1;
                        }
                        stack.push(value);
                    }
                }
                _ => {}
            }
        }
    }
    assert!(seen >= 20, "only {seen} scoped uids in the corpus");
}
